///////////////////////////////////////////////////////////
//  LLErrorEvent.as
//  Macromedia ActionScript Implementation of the Class LLErrorEvent
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:17
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.event
{
	import flash.events.Event;
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:17
	 */
	public class LLErrorEvent extends Event
	{
	    static public const LOAD_ITEM_FAIL: String = "load_item_fail";
	    static public const LOAD_XML_FAIL: String = "load_xml_fail";

		public function LLErrorEvent(type:String, bubbles:Boolean=false, cancelable:Boolean=false){
			super(type, bubbles, cancelable);
		}
		
		public override function clone():Event 
		{ 
			return new LLErrorEvent(type, bubbles, cancelable);
		} 
		
		public override function toString():String 
		{ 
			return formatToString("LLErrorEvent", "type", "bubbles", "cancelable", "eventPhase"); 
		}
		
	}//end LLErrorEvent

}