///////////////////////////////////////////////////////////
//  LLErrorEvent.as
//  Macromedia ActionScript Implementation of the Class LLEvent
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:17
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.event 
{
	import flash.events.Event;
	import org.yukan.data.LLItem;
	
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:17
	 */
	public class LLEvent extends Event 
	{
		public static const CONFIG_SUCCESS:String = "config_success";
		public static const ITEM_COMPLETE:String = "item_complete";
		public static const QUEUE_COMPLETE:String = "queue_complete";
		
		
		//存储item数据
		public var item:LLItem;
		
		public function LLEvent(type:String, bubbles:Boolean=false, cancelable:Boolean=false) 
		{ 
			super(type, bubbles, cancelable);
			
		} 
		
		public override function clone():Event 
		{ 
			var temp:LLEvent = new LLEvent(type, bubbles, cancelable);
			temp.item = this.item;
			
			return temp;
		} 
		
		public override function toString():String 
		{ 
			return formatToString("LLEvent", "type", "bubbles", "cancelable", "eventPhase"); 
		}
		
	}
	
}