///////////////////////////////////////////////////////////
//  ILLType.as
//  Macromedia ActionScript Implementation of the Interface ILLType
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:17
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.data
{
	import org.yukan.gc.IGC;
	import org.yukan.loader.AbstractLoader;
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:17
	 */
	public interface ILLType extends IGC
	{
		 /**
	     * 
	     * @param loader
	     * @param type
	     */
	    function addLoaderType(loader:String, type:String): void;
	    /**
	     * 
	     * @param type
	     */
	    function selectLoader(type:String): AbstractLoader;
	}//end ILLType

}