///////////////////////////////////////////////////////////
//  LLType.as
//  Macromedia ActionScript Implementation of the Class LLType
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:18
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.data
{
	import org.yukan.loader.*;
	import org.yukan.data.ILLType;
	import org.yukan.gc.IGC;
	import flash.utils.getDefinitionByName;
	
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:18
	 */
	public class LLType implements ILLType
	{
		private var typeArr:Object = { 	swf : new SWFLoader(),
										bin : new BLoader(),
										img : new ImageLoader(),
										txt : new TXTLoader() };
										
		public function LLType(){
		}

	    /**
	     * 
	     * @param loader
	     * @param type
	     */
	    public function addLoaderType(loader:String, type:String): void
	    {
			var classIntance:Class = getDefinitionByName(loader) as Class;
			typeArr[type] = new classIntance() as AbstractLoader;
			trace("LLType:"+typeArr[type]);
	    }
		
		//在LLtype中加入顶级程序域
		/*public function set topAppDomain(value:ApplicationDomain):void 
		{
			_topAppDomain = value;
		}*/

	    /**
	     * 
	     * @param type
	     */
	    public function selectLoader(type:String): AbstractLoader
	    {
			trace("所选Loader类型："+typeArr[type]);
			if (typeArr[type] != null) 
				return typeArr[type];
			else 
				return typeArr["bin"];
	    }
		
		//IGC
		public function dispose():void 
		{
			
		}
	}//end LLType

}