///////////////////////////////////////////////////////////
//  AbstractProgressMC.as
//  Macromedia ActionScript Implementation of the Class AbstractProgressMC
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:17
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.loader
{
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:17
	 */
	public class AbstractProgressMC
	{
	    public function AbstractProgressMC()
	    {
	    }

	}//end AbstractProgressMC

}