///////////////////////////////////////////////////////////
//  ILoader.as
//  Macromedia ActionScript Implementation of the Interface ILoader
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:17
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.loader
{
	import flash.events.IEventDispatcher;
	import org.yukan.gc.IGC;
	import org.yukan.data.LLItem;

	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:17
	 */
	public interface ILoader extends IEventDispatcher
	{
		/**
		 * 
		 * @param resource    url
		 */
		function loadItem(item:LLItem): void;
		//function get type():String;
	}//end ILoader

}