///////////////////////////////////////////////////////////
//  LoaderProxy.as
//  Macromedia ActionScript Implementation of the Class LoaderProxy
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:18
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.loader
{
	import org.yukan.data.LLItem;
	import org.yukan.data.LLModel;
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:18
	 */
	public class LoaderProxy extends AbstractLoader
	{
		private var loader:ILoader;
		private var llmodel:LLModel;
		
		public function LoaderProxy(){
			llmodel = LLModel.getInstance();
		}

	    override public function dispose(): void
	    {
	    }


		/**
		 * 
		 * @param resource    url
		 */
		override public function loadItem(item:LLItem): void
		{
			loader = llmodel.selectLoader(item.type);
			loader.loadItem(item)
		}

	}//end LoaderProxy

	
}