///////////////////////////////////////////////////////////
//  IGC.as
//  Macromedia ActionScript Implementation of the Interface IGC
//  Generated by Enterprise Architect
//  Created on:      30-四月-2011 17:52:17
//  Original author: YuKan
///////////////////////////////////////////////////////////

package org.yukan.gc
{
	/**
	 * @author YuKan
	 * @version 1.0
	 * @created 30-四月-2011 17:52:17
	 */
	public interface IGC
	{
		function dispose(): void;
	}//end IGC

}